# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f39c8d1e8fb514c6a3d2cc1d49528cc6629ed66f923d927194508d7a328a55a54ae85556f0e0ce828d08b10c48db7b94b6707d27c5dcd3ea317866ec0295f2c2

test:
  secret_key_base: 3737929ffe26c2c905e6c13e8bd3ddb2260d9cb1ca650be4a7770b23e5cd9765c4b7f43af5c14d7a52e416b1e43e6a1b67a524ade90d73e1e0eb263117b5a6a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
